version: '3'

services:
  server:
    build: .
    ports:
      - "8181:8181"
    volumes:
      - servervol:/serverdata
    networks:
      - my-network

volumes:
  servervol:

networks:
  my-network:
    driver: bridge

